openapi: 3.0.0
info:
  title: LMS API
  version: 1.0.0
  description: API documentation for the LMS system

servers:
  - url: http://localhost:3001/api

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        201:
          description: User registered successfully
        400:
          description: Missing fields or user already exists

  /auth/login:
    post:
      summary: Login user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login successful
        400:
          description: Invalid credentials

  /auth/getMe:
    get:
      summary: Get current user details
      tags: [Auth]
      responses:
        200:
          description: Returns current authenticated user
        401:
          description: Unauthorized

  /auth/logout:
    post:
      summary: Logout current user
      tags: [Auth]
      responses:
        200:
          description: Logged out successfully

  /users:
    get:
      summary: Get all users
      tags: [Users]
      responses:
        200:
          description: List of users

  /users/{id}:
    delete:
      summary: Delete a user by ID
      tags: [Users]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: User deleted
        404:
          description: User not found

  /invite/generate:
    post:
      summary: Generate one-time invite link
      tags: [Invite]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
      responses:
        201:
          description: Invite link created
        400:
          description: Missing email
  /courses:
    post:
      summary: Create a new course
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        '201':
          description: Course created successfully
        '400':
          description: Validation error
        '500':
          description: Server error
    get:
      summary: Get all courses
      responses:
        '200':
          description: Courses retrieved successfully
        '500':
          description: Server error
  /courses/{id}:
    get:
      summary: Get course by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Course retrieved
        '404':
          description: Course not found
    put:
      summary: Update a course by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        '200':
          description: Course updated
        '404':
          description: Course not found
    delete:
      summary: Delete a course by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Course deleted
        '404':
          description: Course not found
components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    Course:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        syllabusLink:
          type: string
        teacher:
          type: string
        students:
          type: array
          items:
            type: string
        materials:
          type: array
          items:
            type: string
        schedule:
          type: array
          items:
            type: object
            properties:
              day:
                type: string
              startHour:
                type: string
              endHour:
                type: string
              location:
                type: object
                properties:
                  name:
                    type: string
                  lat:
                    type: number
                  lng:
                    type: number
                  radiusMeters:
                    type: number